/* this file was generated by linkcmd.xdt from the gnu.targets.arm
 * package
 */
INPUT(
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-codec-engine-tree/packages/ti/sdo/ce/utils/trace/lib/release/TraceUtil.av5T
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-codec-engine-tree/packages/ti/sdo/ce/bioslog/lib/release/bioslog.av5T
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-dmai-tree/packages/ti/sdo/dmai/lib/dmai_linux_dm6446.a470MV
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-codec-engine-tree/packages/ti/sdo/ce/image/lib/release/image.av5T
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-codec-engine-tree/packages/ti/sdo/ce/video/lib/release/video.av5T
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-codec-engine-tree/packages/ti/sdo/ce/audio/lib/release/audio.av5T
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-codec-engine-tree/packages/ti/sdo/ce/speech/lib/release/speech.av5T
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-codec-engine-tree/packages/ti/sdo/ce/video1/lib/release/viddec1.av5T
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-codec-engine-tree/packages/ti/sdo/ce/video1/lib/release/videnc1.av5T
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-codec-engine-tree/packages/ti/sdo/ce/speech1/lib/release/sphdec1.av5T
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-codec-engine-tree/packages/ti/sdo/ce/speech1/lib/release/sphenc1.av5T
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-codec-engine-tree/packages/ti/sdo/ce/audio1/lib/release/auddec1.av5T
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-codec-engine-tree/packages/ti/sdo/ce/audio1/lib/release/audenc1.av5T
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-codec-engine-tree/packages/ti/sdo/ce/image1/lib/release/imgdec1.av5T
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-codec-engine-tree/packages/ti/sdo/ce/image1/lib/release/imgenc1.av5T
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-codec-engine-tree/packages/ti/sdo/ce/video2/lib/release/viddec2.av5T
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-codec-engine-tree/packages/ti/sdo/ce/lib/release/ce.av5T
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-codec-engine-tree/packages/ti/sdo/ce/alg/lib/release/Algorithm_noOS.av5T
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-codec-engine-tree/packages/ti/sdo/ce/alg/lib/release/alg.av5T
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-codec-engine-tree/packages/ti/sdo/ce/ipc/dsplink/lib/release/ipc_dsplink_6446.av5T
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-codec-engine-tree/packages/ti/sdo/ce/osal/linux/lib/release/osal_linux_470.av5T
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-framework-components-tree/packages/ti/sdo/fc/acpy3/lib/release/acpy3.a470MV
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-framework-components-tree/packages/ti/sdo/fc/dman3/lib/release/dman3Cfg.a470MV
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-framework-components-tree/packages/ti/sdo/fc/utils/lib/release/rmm.av5T
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-framework-components-tree/packages/ti/sdo/fc/utils/lib/release/smgr.av5T
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-framework-components-tree/packages/ti/sdo/fc/utils/lib/release/rmmp.av5T
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-framework-components-tree/packages/ti/sdo/fc/utils/lib/release/smgrmp.av5T
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-framework-components-tree/packages/ti/sdo/fc/utils/lib/release/shm.av5T
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-framework-components-tree/packages/ti/sdo/fc/memutils/lib/release/memutils.av5T
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-codec-engine-tree/packages/ti/sdo/ce/node/lib/release/node.av5T
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-linuxutils-tree/packages/ti/sdo/linuxutils/cmem/lib/cmem.a470MV
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-dsplink-tree/dsplink/gpp/export/BIN/Linux/DAVINCI/RELEASE/dsplink.lib
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-codec-engine-tree/packages/ti/sdo/ce/utils/xdm/lib/release/XdmUtils.av5T
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-framework-components-tree/packages/ti/sdo/utils/trace/lib/release/gt.av5T
    /home/caglar/myfs/work/tasks/openembedded/old/build/tmp/sysroots/bilkon-blec32-angstrom-linux-gnueabi/usr/share/ti/ti-xdctools-tree/packages/gnu/targets/arm/rtsv5T/lib/gnu.targets.arm.rtsv5T.av5T
)

SECTIONS {
    xdc.meta (COPY) : {*(xdc.meta)}

}

INSERT BEFORE .gnu.attributes
